spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: ${spring.application.name}-${spring.profiles.active}
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 2
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            tablePrefix: QRTZ_
            dataSource: quartzdatasource
          datasource:
            quartzdatasource:
              driver: com.mysql.jdbc.Driver
              url: jdbc:mysql://rm-2vcm51t57o2449u38ao.mysql.cn-chengdu.rds.aliyuncs.com:3306/quartz?characterEncoding=utf8&allowMultiQueries=true
              username: root
              password: deocean@123
              maxConnections: 5
              hikari:
                maximum-pool-size: 4
                idle-timeout: 60000
                minimum-idle: 2
    job-store-type: JDBC
    jdbc:
      initialize-schema: NEVER